import { ProjectOption, ReviewItem, FaqItem } from './types';

export const PROJECT_OPTIONS: ProjectOption[] = [
  {
    id: 'perso',
    title: 'Prêt Personnel / Trésorerie',
    shortName: 'Trésorerie & Vie courante',
    iconName: 'Wallet',
    description: 'Financez vos envies librement sans obligation de fournir de devis ou facture d’achat.',
    minAmount: 1000,
    maxAmount: 50000,
    defaultAmount: 8000,
    minMonths: 12,
    maxMonths: 84,
    defaultMonths: 48,
    baseRate: 3.85,
    popularBadge: 'Le plus populaire',
  },
  {
    id: 'auto',
    title: 'Crédit Auto & Moto',
    shortName: 'Véhicule Neuf / Occasion',
    iconName: 'Car',
    description: 'Achetez votre nouvelle voiture, moto ou scooter au meilleur taux garanti chez R-Financial.',
    minAmount: 2000,
    maxAmount: 60000,
    defaultAmount: 15000,
    minMonths: 12,
    maxMonths: 84,
    defaultMonths: 60,
    baseRate: 3.49,
    popularBadge: 'Taux attractif',
  },
  {
    id: 'travaux',
    title: 'Prêt Travaux & Déco',
    shortName: 'Rénovation & Maison',
    iconName: 'Hammer',
    description: 'Donnez vie à vos projets d’aménagement, cuisine, salle de bain, terrasse ou extension.',
    minAmount: 1500,
    maxAmount: 75000,
    defaultAmount: 12000,
    minMonths: 12,
    maxMonths: 84,
    defaultMonths: 48,
    baseRate: 3.65,
  },
  {
    id: 'eco',
    title: 'Crédit Éco-Responsable',
    shortName: 'Rénovation Énergétique',
    iconName: 'Leaf',
    description: 'Pompes à chaleur, panneaux solaires, isolation thermique avec notre taux bonifié vert.',
    minAmount: 3000,
    maxAmount: 60000,
    defaultAmount: 14000,
    minMonths: 12,
    maxMonths: 84,
    defaultMonths: 60,
    baseRate: 2.99,
    popularBadge: 'Taux Vert 2.99%',
  },
  {
    id: 'rachat',
    title: 'Rachat de Crédits',
    shortName: 'Regroupement de prêts',
    iconName: 'RefreshCw',
    description: 'Regroupez tous vos emprunts en une seule mensualité réduite et simplifiez votre budget.',
    minAmount: 5000,
    maxAmount: 100000,
    defaultAmount: 22000,
    minMonths: 24,
    maxMonths: 84,
    defaultMonths: 72,
    baseRate: 4.75,
  },
  {
    id: 'imprevu',
    title: 'Coup Dur / Imprévu Express',
    shortName: 'Besoin Urgent 24-48h',
    iconName: 'Zap',
    description: 'Une dépense imprévue, santé, réparation urgente ? Déblocage ultra-rapide sous 48h ouvrées.',
    minAmount: 1000,
    maxAmount: 10000,
    defaultAmount: 3000,
    minMonths: 6,
    maxMonths: 36,
    defaultMonths: 24,
    baseRate: 5.20,
  },
];

export const TRUST_PILLARS = [
  {
    title: 'Réponse de principe en 3 min',
    desc: 'Analyse instantanée et simulation gratuite sans engagement.',
    icon: 'Clock',
  },
  {
    title: '100% En Ligne & Zéro Papier',
    desc: 'Parcours simplifié sans démarche lourde en agence.',
    icon: 'ShieldCheck',
  },
  {
    title: 'Transparence & Zéro Frais Cachés',
    desc: 'Aucun frais de dossier, taux fixe garanti sur toute la durée.',
    icon: 'Building2',
  },
  {
    title: 'Accompagnement Dédié',
    desc: 'Un interlocuteur unique pour étudier et suivre votre dossier de financement.',
    icon: 'Star',
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: '01',
    title: 'Simulez en 2 minutes',
    desc: 'Sélectionnez votre projet, le montant et la durée idéale pour calculer votre mensualité fixe.',
    highlight: 'Gratuit et sans aucun engagement',
  },
  {
    step: '02',
    title: 'Complétez votre demande 100% en ligne',
    desc: 'Renseignez vos informations en quelques clics. Zéro justificatif requis à cette étape initiale.',
    highlight: 'Processus simplifié et 100% confidentiel',
  },
  {
    step: '03',
    title: 'Recevez vos fonds sous 48h',
    desc: 'Après validation définitive de votre offre, vos fonds sont virés directement sur votre compte bancaire habituel.',
    highlight: 'Délai légal de rétractation de 14 jours respecté',
  },
];

export const REVIEWS: ReviewItem[] = [
  {
    id: '1',
    author: 'Marc D.',
    city: 'Bordeaux',
    rating: 5,
    date: 'Il y a 3 jours',
    amount: 14000,
    project: 'Achat Voiture Hybride',
    comment: 'Expérience remarquable avec R-Financial group ! Accord de principe obtenu en 2 minutes chrono et virement reçu sur mon compte très rapidement. Zéro mauvaise surprise.',
    verified: true,
  },
  {
    id: '2',
    author: 'Sophie L.',
    city: 'Nantes',
    rating: 5,
    date: 'Il y a 1 semaine',
    amount: 9500,
    project: 'Rénovation Cuisine',
    comment: 'L’interface de simulation est d’une clarté totale, avec un conseiller R-Financial très disponible et réactif par e-mail pour finaliser le dossier.',
    verified: true,
  },
  {
    id: '3',
    author: 'Alexandre B.',
    city: 'Lyon',
    rating: 5,
    date: 'Il y a 2 semaines',
    amount: 26000,
    project: 'Rachat de crédits',
    comment: 'J’ai pu regrouper mon prêt auto et deux réserves d’argent. Ma mensualité globale est passée de 680€ à 395€ par mois. Une vraie respiration pour notre foyer !',
    verified: true,
  },
  {
    id: '4',
    author: 'Camille & Julien V.',
    city: 'Lille',
    rating: 5,
    date: 'Il y a 3 semaines',
    amount: 5000,
    project: 'Trésorerie & Naissance',
    comment: 'Simple, rapide, moderne. Pas besoin de changer de banque, tout se fait en ligne en toute sérénité. Je recommande les yeux fermés.',
    verified: true,
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    category: 'Général',
    question: 'Qu’est-ce qui différencie R-Financial group d’une banque traditionnelle ?',
    answer: 'R-Financial group est une FinTech 100% en ligne accessible à l’international. Sans le coût d’agences physiques, nous répercutons ces économies directement sur vos taux d’intérêt avec 0 € de frais de dossier, une simulation immédiate et un accompagnement personnalisé par un conseiller dédié.',
  },
  {
    category: 'Délais',
    question: 'En combien de temps mon dossier est-il traité ?',
    answer: 'Dès validation de votre formulaire de pré-éligibilité (Zéro Document requis à cette étape), un conseiller dédié prend contact avec vous sous 24h à 48h ouvrées avec votre offre personnalisée.',
  },
  {
    category: 'Taux & Frais',
    question: 'Le taux TAEG est-il fixe pendant toute la durée du crédit ?',
    answer: 'Oui, à 100%. Chez R-Financial group, tous nos crédits sont à taux débiteur fixe et mensualités constantes en Euros (€). Vos mensualités ne varieront jamais durant toute la durée de votre remboursement.',
  },
  {
    category: 'Remboursement',
    question: 'Puis-je rembourser mon prêt par anticipation sans pénalité ?',
    answer: 'Oui ! Conformément à la réglementation bancaire européenne, vous pouvez effectuer un remboursement anticipé partiel ou total à tout moment.',
  },
  {
    category: 'Documents',
    question: 'Faut-il envoyer des pièces justificatives dès la demande en ligne ?',
    answer: 'Non ! Conformément à notre stratégie Zéro Document à l’étape 1, aucune pièce d’identité ni fiche de paie n’est demandée sur le site. Les pièces justificatives seront transmises ultérieurement par simple réponse par e-mail direct à votre conseiller.',
  },
];

export const COUNTRY_LIST = [
  'France',
  'Belgique',
  'Suisse',
  'Luxembourg',
  'Allemagne',
  'Espagne',
  'Italie',
  'Portugal',
  'Royaume-Uni',
  'Pays-Bas',
  'Canada',
  'États-Unis',
  "Côte d'Ivoire",
  'Sénégal',
  'Bénin',
  'Cameroun',
  'Togo',
  'Gabon',
  'Congo',
  'Mali',
  'Burkina Faso',
  'Guinée',
  'Madagascar',
  'Maroc',
  'Algérie',
  'Tunisie',
  'Autre pays (Union Européenne)',
  'Autre pays (International)',
];

export const PHONE_INDICATIVES = [
  { code: '+33', country: 'France', flag: '🇫🇷' },
  { code: '+32', country: 'Belgique', flag: '🇧🇪' },
  { code: '+41', country: 'Suisse', flag: '🇨🇭' },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺' },
  { code: '+49', country: 'Allemagne', flag: '🇩🇪' },
  { code: '+34', country: 'Espagne', flag: '🇪🇸' },
  { code: '+39', country: 'Italie', flag: '🇮🇹' },
  { code: '+351', country: 'Portugal', flag: '🇵🇹' },
  { code: '+44', country: 'Royaume-Uni', flag: '🇬🇧' },
  { code: '+31', country: 'Pays-Bas', flag: '🇳🇱' },
  { code: '+1', country: 'USA / Canada', flag: '🇺🇸' },
  { code: '+225', country: "Côte d'Ivoire", flag: '🇨🇮' },
  { code: '+221', country: 'Sénégal', flag: '🇸🇳' },
  { code: '+229', country: 'Bénin', flag: '🇧🇯' },
  { code: '+237', country: 'Cameroun', flag: '🇨🇲' },
  { code: '+228', country: 'Togo', flag: '🇹🇬' },
  { code: '+241', country: 'Gabon', flag: '🇬🇦' },
  { code: '+212', country: 'Maroc', flag: '🇲🇦' },
  { code: '+213', country: 'Algérie', flag: '🇩🇿' },
  { code: '+216', country: 'Tunisie', flag: '🇹🇳' },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬' },
];

export const PROFESSIONAL_SITUATIONS = [
  'Salarié(e) en CDI',
  'Fonctionnaire / Agent public',
  'Salarié(e) en CDD / Intérim',
  'Indépendant / Profession libérale',
  'Chef d’entreprise / Commerçant',
  'Retraité(e)',
  'Sans emploi',
  'Autre situation',
];

